### ISSUE TITLE
global path planning : mapdataの受け取り、二次元配列変換

### ISSUE THREAD

**Issue by tsuchiya-i** [amslabtech/chibi19_b#11]

**Comment by Wataru-Y** [comment]
$ rosrun map_server map_server ~/mapdata/DMapData.yaml
GTUNE上でこれを実行すれば、"/map"が配信される

**Comment by tsuchiya-i** [comment]
> >$ rosrun map_server map_server ~/mapdata/DMapData.yaml
> >GTUNE上でこれを実行すれば、"/map"が配信される
学校のPCには入ってるのか！
mapdataの中にnavigationパッケージのインストール方法載せいたよ。
自分のパソコンでもmap_server使えるはず。

**Comment by tsuchiya-i** [comment]
map_serverから地図データをsubscribeできるようになった。
4000x4000の配列に入れることができた。
