### ISSUE TITLE
Localization:レンジに基づく重み付け

### ISSUE THREAD

**Issue by Wataru-Y** [amslabtech/chibi19_b#16]

**Comment by ykuroda513** [comment]
どういう重み付けをするんですか？　目的は何ですか？

**Comment by Wataru-Y** [comment]
LIDARからのスキャンデータとパーティクルごと参照スキャンデータの差から尤度を求め、それらを正規化することで重み付けを行います．
最終的に、それらを用いてリサンプリングや自己位置推定を行います．
